### ISSUE TITLE
Converting base stats and other data to the correct value

### ISSUE THREAD

**Issue by justuscook** [Da-Teach/RaidStaticData#5]
All base stats and some other values seem so be obfuscated in some way. Has anyone been able to figure out how to decipher them.  I think it was discussed some how in the old extractor repo issues but that's gone now.  Any help is greatly appreciated.

**Comment by grBIN** [comment]
According to the main characteristics, @Da-Teach has already answered, the values of the value must be divided by 2 ^ 32 = 4294967296

However, some values like the HP of the defense attack - there are additional coefficients that I have not yet been able to figure out - at least it is clear that they depend on the rarity of the hero. If you find - please write =)

**Comment by grBIN** [comment]
In one of the repositories I found such numbers - for 6 stars 60lvl the attack / defense multiplier is 11.0117, health - 11.0117 * 15

But it looks like I'm doing something wrong in the calculations...

**Comment by vnoctem** [comment]
Scalable stats such as ATK, DEF and HP have a pair of multipliers that need to be applied as well to get the actual values.
The pair of multipliers depends on the rank level (1 to 6) of the champion.
For HP, you also need to multiply by 15.

Formulas: 
ATK, DEF = Raw_value_in_JSON / (2 ^ 32) * Multiplier_1 * Multiplier_2
HP = Raw_value_in_JSON / (2 ^ 32) * Multiplier_1 * Multiplier_2 * 15

   Rank level    | MULTIPLIER_1 | MULTIPLIER_2       
        1               |  1                     |  2
        2              |  1.60000002  |  1.89999998
        3              |  2.43199992  |  1.79999995
        4              |  3.50207996  |  1.70000005
        5              |  4.76282883  |  1.70000005
        6              |  6.47744703  |  1.70000005

I have used these values in one of my personal projects (https://github.com/vnoctem/raid-data-parser/blob/main/src/main/java/com/vg/raiddataparser/parser/DataParser.java)

Hope it helps.

**Comment by grBIN** [comment]
What i do wrong?

`    hero.attackJSON = inputHero.BaseStats.Attack`
`    hero.attackINT = hero.attackJSON / Math.pow(2, 32);`
`    hero.attackDoubleMod = Math.round(hero.attackINT * 6.47744703 * 1.70000005);`
`    hero.attackSingleMod = Math.round(hero.attackINT * 11.0117);`

  '5790': {
    id: 5790,
    name: 'Godseeker Aniri',
    attackJSON: 386547056640,
    attackINT: 90,
    attackDoubleMod: 991,
    attackSingleMod: 991,
    realAttack: 1046
  },
  '5800': {
    id: 5800,
    name: 'Countess Lix',
    attackJSON: 515396075520,
    attackINT: 120,
    attackDoubleMod: 1321,
    attackSingleMod: 1321,
    realAttack: 1498
  }

**Comment by grBIN** [comment]
I solved this problem, the problem is not in calculations, but in objects.
Up to this point, I have selected heroes from HeroTypes by ID based on the HeroIdsByRarities object (To get only playable characters).
It turned out that the IDs of the basic characters are indicated there, and the basic stats are indicated there less than necessary.
Just take the correct object with the hero and apply the above mentioned coefficients - everything will be fine =)

**Comment by justuscook** [comment]
Just FYI you need to round the number before you multiply for health., other than that these numbers work well.  Thanks guys!

**Comment by anbecker** [comment]
FWIW, I believe the actual numbers are as follows:

Get base stat by dividing raw value by 2^32.

Ranking up confers a certain benefit for each rank. To account for these...
For rank 2, multiply by 1.6.
For rank 3, multiply by 1.6 * 1.52.
For rank 4, multiply by 1.6 * 1.52 * 1.44.
For rank 5, multiply by 1.6 * 1.52 * 1.44 * 1.36.
For rank 6, multiply by 1.6 * 1.52 * 1.44 * 1.36 * 1.36.

This will give you the stat at level 1. The stat at max level is as follows:
For rank 1 champs, it is 2.0 * the stat at level 1.
For rank 2 champs, it is 1.9 * the stat at level 1.
For rank 3 champs, it is 1.8 * the stat at level 1.
For rank 4 champs, it is 1.7 * the stat at level 1.
For rank 5 champs, it is 1.7 * the stat at level 1.
For rank 6 champs, it is 1.7 * the stat at level 1.

The stat scaling by level is geometric - meaning the stat is multiplied by some constant value each level such that it reaches the appropriate value at max level.

Since the maximum level is different for different ranks, as is the stat value when compared with level 1, this constant is different for each rank.

For a 6* champion, we can do some math to find that it would be equal to e^(ln(1.7)/59), since multiplying by it 59 times will result in a 1.7x overall boost (level 60 stats are 1.7x what they are at level 1).
